### ISSUE TITLE
Allow TextFields inside of Flash?

### ISSUE THREAD

**Issue by johnmastri** [sososdk/flash#1]
Maybe I'm using this in a less conventional way, but I have a couple form fields I'm trying to put in the flash. Is there any way to activate them?

![image](https://user-images.githubusercontent.com/1303044/64916963-79f10800-d747-11e9-859c-826d993c7d0f.png)

**Comment by sososdk** [comment]
Maybe you can do something like this: [_showInputFlash](https://github.com/sososdk/flash/blob/2d2a1c5f655c7160e66033bfe52b10f8e5f37a66/example/lib/main.dart#L342)
