### ISSUE TITLE
overlay can't be the root overlay when persistent is false

### ISSUE THREAD

**Issue by krzysztofgarnys** [sososdk/flash#11]
error message: overlay can't be the root overlay when persistent is false
eg. when I am using blogDialog in my app

**Comment by dheerajbred** [comment]
Any solution?

> error message: overlay can't be the root overlay when persistent is false
> eg. when I am using blogDialog in my app

**Comment by wish32** [comment]
I have the same problem , Any solution?

**Comment by sososdk** [comment]
Hi @wish32 @dheerajbred , wrap you page with `Overlay`:

```dart
Navigator.of(context).push(MaterialPageRoute(builder: (context) {
        return Overlay(
          initialEntries: [
            OverlayEntry(builder: (context) {
              return FlashPage();
            }),
          ],
        );
      }));
```

**Comment by wish32** [comment]
Thank you for your reply. But I don`t know how to use Overlay to wrap my page. Thank you anyway!

**Comment by sososdk** [comment]
Wrap `MyPage` with `Overlay`:
```dart
Navigator.of(context).push(MaterialPageRoute(builder: (context) {
        return Overlay(
          initialEntries: [
            OverlayEntry(builder: (context) {
              return MyPage();
            }),
          ],
        );
      }));
```

Use `persistent: false`:
```dart
class MyPage extends StatefulWidget {
  @override
  _MyPageState createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {
    return Center(child: RaisedButton(child: Text('dialog'), onPressed: () {
      showFlash(
        context: context,
        persistent: false,
        duration: const Duration(milliseconds: 300),
        builder: (context, controller) {
          return Flash(
            controller: controller,
            horizontalDismissDirection: HorizontalDismissDirection.horizontal,
            child: FlashBar(
              message: Text('This is a basic flash'),
            ),
          );
        },
      );
    },),);
  }
}
```

**Comment by pharshdev** [comment]
> Hi @wish32 @dheerajbred , wrap you page with `Overlay`:
> 
> ```dart
> Navigator.of(context).push(MaterialPageRoute(builder: (context) {
>         return Overlay(
>           initialEntries: [
>             OverlayEntry(builder: (context) {
>               return FlashPage();
>             }),
>           ],
>         );
>       }));
> ```

this on flutter web gives 
`BindingError: Expected null or instance of Typeface, got an instance of Typeface
`

**Comment by easazade** [comment]
i can't tell whether this is a fix or the normal solution. looks like a hack.

**Comment by sososdk** [comment]
Hello @easazade , I designed it this:  when `persistent` is false, we use the page's own `Overlay` and add a `LocalHistoryEntry` to the page route.

**Comment by easazade** [comment]
@sososdk i appreciate a fast response on GitHub any day 👍
