### ISSUE TITLE
when a Flash appears, it hides the keyboard 

### ISSUE THREAD

**Issue by AymanProjects** [sososdk/flash#17]
the forgot password will show a dialog on click. but it hides the keyboard.
It also happens when a snackbar appears.

![untitled](https://user-images.githubusercontent.com/67029027/106508813-e061fc00-64dd-11eb-8025-6de45d38ce23.gif)

**Comment by AymanProjects** [comment]
I modified the source code and it no longer hides the keyboard.
I just commented the unwanted code as shown in the image.
anyway this is not really elegant and the package is now stored locally with the my project files.
maybe you could make this feature optional ?
![image](https://user-images.githubusercontent.com/67029027/106513476-1904d400-64e4-11eb-8243-9326c6807229.png)

**Comment by sososdk** [comment]
Hi @AymanProjects,  Now the code is as expected. Maybe you need add `autofocus: true` in `TextFormField` or `TextField`.

Example:
```dart
    Form(
      child: TextFormField(
        controller: editingController,
        autofocus: true,
      ),
    )
```

**Comment by AymanProjects** [comment]
That solved the problem, Thanks ♥

**Comment by ming-chu** [comment]
I have the same issue, how to prevent interrupt the typing when Flash appears?
Any help is appreciated!

**Comment by sososdk** [comment]
> Hi @AymanProjects, Now the code is as expected. Maybe you need add `autofocus: true` in `TextFormField` or `TextField`.
> 
> Example:
> 
> ```dart
>     Form(
>       child: TextFormField(
>         controller: editingController,
>         autofocus: true,
>       ),
>     )
> ```

@ming-chu example: https://github.com/sososdk/flash/blob/839f8c28700948f3ab7bad81d66f3def2b333874/example/lib/main.dart#L421

**Comment by ming-chu** [comment]
@sososdk  Thanks for your reply.

Here is my case:
I use this lib for the top bar notification, maybe with frequency like 20 times/minutes.
when users typing and respond to the msg, this will interrupt the typing.

**Comment by sososdk** [comment]
@ming-chu which one interrupt the typing?

**Comment by ming-chu** [comment]
@sososdk 
I am developing a chat app. I use this lib for showing new message notifications.
When `Flash` appears, it blocks the entire screen with overlay and closes the keyboard.
The input will focus again after the `Flash` is finished, but the typing is interrupted which cannot keep typing when the `Flash` show up.

**Comment by sososdk** [comment]
@ming-chu please show me the code about how to display the flash.

**Comment by ming-chu** [comment]
@sososdk  Thanks for the reply and here is the code
```dart
showFlash(
  context: context,
  duration: const Duration(seconds: 2),
  persistent: true,
  builder: (_, controller) {
    return Flash(
      controller: controller,
      backgroundColor: Colors.white,
      brightness: Brightness.light,
      boxShadows: [BoxShadow(blurRadius: 4)],
      barrierBlur: 3.0,
      barrierColor: Colors.black38,
      barrierDismissible: true,
      behavior: FlashBehavior.floating,
      position: FlashPosition.top,
      child: FlashBar(
        title: Text('You have a new msg!'),
        content: Text('hello world~'),
      ),
    );
  },
);
```

**Comment by sososdk** [comment]
@ming-chu try to set `persistent: false` .

**Comment by ming-chu** [comment]
after I set `persistent: false` it got an exception 🤔
```plain text
E/flutter ( 5759): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flash/flash.dart': Failed assertion: line 98 pos 14: 'overlay != rootOverlay': overlay can't be the root overlay when persistent is false
E/flutter ( 5759): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 5759): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 5759): #2      new FlashController (package:flash/flash.dart:98:14)
E/flutter ( 5759): #3      showFlash (package:flash/flash.dart:25:10)
```

**Comment by sososdk** [comment]
@ming-chu try to remove `barrierBlur` and `barrierColor` and set `persistent: true`.

**Comment by ming-chu** [comment]
> @ming-chu try to remove `barrierBlur` and `barrierColor`, and set `persistent: true`.   
> 
> 
> 
> `barrierBlur` and `barrierColor` will block the behind view.

Thanks for the advice, I will try it👍

**Comment by ming-chu** [comment]
@sososdk 
it works!!! Thank you very much! 
You are my hero!
