### ISSUE TITLE
Overlay is null when using a GlobalKey<NavigatorState>

### ISSUE THREAD

**Issue by sky-joaopalma** [sososdk/flash#21]
I'm trying to call showFlash with a navigatorState:

`showFlash(context: _navigator.currentState.context, persistent: false, builder: (context, controller) {`

But the overlay is null.

I already tried to add an Overlay when generating a route:

```
Route<dynamic> _generateRoute(RouteSettings settings) {
    return MaterialPageRoute(settings: settings, builder: (_) => Overlay(
          initialEntries: [OverlayEntry(builder: (context) => view )]
    ));
  }
```

**Comment by sososdk** [comment]
You need to use the `context` that contains a `Overlay`.
