### ISSUE TITLE
Flash Dialog and SafeArea

### ISSUE THREAD

**Issue by iberatkaya** [sososdk/flash#26]
Hello. Is there a way to disable the SafeArea in dialogs similar to Flutter's [`showDialog`](https://api.flutter.dev/flutter/material/showDialog.html) and its `useSafeArea` parameter? If there is not, would you consider adding such a feature and/or accepting PR's?

> The useSafeArea argument is used to indicate if the dialog should only display in 'safe' areas of the screen not used by the operating system (see SafeArea for more details). It is true by default, which means the dialog will not overlap operating system areas. If it is set to false the dialog will only be constrained by the screen size. It can not be null.

**Comment by sososdk** [comment]
Hi @iberatkaya , `useSafeArea` parameter was added in `Flash`, please use `2.0.1` https://github.com/sososdk/flash/blob/cb8de546fb923a883833a89bb68623723bc96e66/lib/flash.dart#L455

Usage:
```dart
showFlash(
  context: context,
  builder: (_, controller) {
    return Flash(
      controller: controller,
      useSafeArea: false, // default is true
      child: FlashBar(
        title: Text('Title'),
        content: Text('Hello world!'),
      ),
    );
  },
);
```
