### ISSUE TITLE
FocusScopeNode Error

### ISSUE THREAD

**Issue by antoniopetricc** [sososdk/flash#30]
FocusScopeNode FocusScopeNode#ea86b(_FlashState<dynamic> Focus Scope [PRIMARY FOCUS])(context: FocusScope, PRIMARY FOCUS) must be a child of FocusScopeNode#6ff27(Navigator Scope)(context: FocusScope, focusedChildren: [FocusScopeNode#bac68(_ModalScopeState<dynamic> Focus Scope)]) to set it as first focus.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 1272 pos 12: 'scope.ancestors.contains(this)'

**Comment by anthonysette** [comment]
How did you solve this?

**Comment by anthonysette** [comment]
Where did you call this though? Does the issue not relate to the flash snackbars?

**Comment by mkPytsNortal** [comment]
For those who are trying to add a text field into Flash, please do not use **persistent: true**, in this case Flash it is not using navigator overlay and during the typing into the text field didUpdateWidget is trying to make magic with FocusNodeScopes or Navigator FocusScopeNode and Flash's state FocusScopeNode
