### ISSUE TITLE
showToast in center or any other location

### ISSUE THREAD

**Issue by kevzzsk** [sososdk/flash#33]
How do you showToast in any other location?

Currently `context.showToast()` places the toast at a weird between center to bottom location.

edit:
Okay found a way to adjust the alignment with:
```dart
// Wrap with toast.
    child = Toast(
      child: child,
      navigatorKey: navigatorKey,
      alignment: Alignment.topCenter,
    );
```

but this works only on the init, so it is currently not possible to change the alignment on `showToast`. maybe add optional argument in `showToast` to specify the location of toast?

If this sounds good, I can send a PR

**Comment by sososdk** [comment]
I added some optional parameters for 'Toast' in '2.0.2':

```dart
Future<T?> showToast<T>(
    Object message, {
    Duration duration = const Duration(seconds: 3),
    Alignment? alignment,
    EdgeInsets? margin,
    BorderRadius? borderRadius,
    Color? backgroundColor,
    TextStyle? textStyle,
    EdgeInsets? padding,
  })
```
