### ISSUE TITLE
Flutter web dialog size

### ISSUE THREAD

**Issue by herman-the-worm** [sososdk/flash#37]
Hello,

We use this package extensively in our projects.

Is there a way to specify the size of the Dialog window? We are running blockers in Flutter web when we do not have a way to limit the size of the dialog width.

Any existing settings that we can use to adjust it? (context.showFlashDialog)

Thanks

**Comment by sososdk** [comment]
Hi @herman-the-worm , I added  a `constraints` optional params. 

```dart
context.showFlashDialog(
        constraints: BoxConstraints(maxWidth: 300),
       ...
);
```
