### ISSUE TITLE
Popup widgets are behind the flash widget

### ISSUE THREAD

**Issue by benedict1986** [sososdk/flash#40]
Hi @sososdk ,

Thank you for building such great tool. When I am using it (version ^2.0.3+1), I find that the popup widgets are behind the flash widget.

For example, I try to add a dropdown button in a `context.showFlashDialog<T>`, but the dropdown list is behind the dialog. I also use a date time picker in a bottom sheet, but the popup date time picker also behind the bottom sheet.

![image](https://user-images.githubusercontent.com/7417859/150682035-59a9bf71-1d90-4b44-ae87-b1c726ffa548.png)

Here is the example code I am using

```
await showFlash(
      context: context,
      builder: (_, controller) {
        return Flash(
          controller: controller,
          behavior: FlashBehavior.fixed,
          position: FlashPosition.bottom,
          onTap: () => controller.dismiss(),
          forwardAnimationCurve: Curves.easeInCirc,
          reverseAnimationCurve: Curves.bounceIn,
          child: SomeWidgetIncludingTheDateTimePicker(),
        );
```

Can you please take a look and see if there is anything I missed.

Thank you

**Comment by sososdk** [comment]
For this scenario, it is recommended to set `persistent: false`.

In this case, you must wrap you page with `Overlay`, see [example](https://github.com/sososdk/flash/blob/78617abfb8ef25fef6a715c877095d95be95f262/example/lib/main.dart?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L79).

Then call flash:
```dart
    context.showFlashDialog(
        persistent: false,
        ......
    );
```

**Comment by benedict1986** [comment]
Thank you @sososdk. It's working.
