### ISSUE TITLE
Add FlashBar blur

### ISSUE THREAD

**Issue by ninoid** [sososdk/flash#48]
Please provide blur effect for flashbar. This can be very nice when customized.

**Comment by sososdk** [comment]
@ninoid 
you can use [barrierBlur](https://github.com/sososdk/flash/blob/948edfedce2da5a1d5c33f382f6d5a3cb9e9c752/lib/flash.dart#L437) and [barrierColor](https://github.com/sososdk/flash/blob/948edfedce2da5a1d5c33f382f6d5a3cb9e9c752/lib/flash.dart#L440)

**Comment by ninoid** [comment]
> 

Thanks for response. Background of flashbar should have blur effect.

**Comment by ninoid** [comment]
> 

@sososdk Thanks for response. Background of flashbar should have blur effect.
