### ISSUE TITLE
QUESTION: is it possible to push a route or dialog in such a way that the Flash is covered behind the new route ?

### ISSUE THREAD

**Issue by gbaccetta** [sososdk/flash#51]
Hello! Thanks for the hard work. is this possible ?

**Comment by sososdk** [comment]
Flash base on `Overlay` and cannot use route.

**Comment by gbaccetta** [comment]
Yup got it, but even if I do (using same context and navigator):
- showFlash
- showGeneralDialog
I expect the generalDialog to be on top of the Flash, but it remains under it.

**Comment by sososdk** [comment]
Wrap you page with [`Overlay`](https://github.com/sososdk/flash/blob/5a4c49dc86afd01cad15e1a6b404189365870f80/example/lib/main.dart#L79) and set [`persistent`](https://github.com/sososdk/flash/blob/5a4c49dc86afd01cad15e1a6b404189365870f80/lib/flash.dart#L22) to false.

```dart
showFlash(persistent: false)
```

Usually I use [auto_route](https://pub.dev/packages/auto_route) to automatically wrap all pages with `Overlay`.

**Comment by gbaccetta** [comment]
Well I actually achieved what I wanted by using showFlash also for my Route (which act as sort of guard).

However this was intercepting back button press before, using flash, the back button event is passed to the route behind it... is there a way to intercept and block back button in a Flash ?

**Comment by gbaccetta** [comment]
maybe not the best, but I found a solution, as of all my view inherited from a base view I just wrapped that in a willPopScope looking at a static variable that check if my top guard view is visible as a Flash

**Comment by sososdk** [comment]
`showFlash` method has `onWillPop` parameter, you can try it.

```dart
showFlash(onWillPop: ...)
```
