### ISSUE TITLE
Error with 'foregroundColor '

### ISSUE THREAD

**Issue by tobelesa** [sososdk/flash#54]
Hello,
it seems that with new flutter versions and new Android APIs Flash package code raises an error : 

Error: No named parameter with the name 'foregroundColor'.
`style: TextButton.styleFrom(foregroundColor: $actionColor),`

Is it related to a change in Flutter's way to type styles?
https://docs.flutter.dev/release/breaking-changes/buttons

Thanks,
Sam

**Comment by sososdk** [comment]
Yes, reference #52 .
