### ISSUE TITLE
Cannot reuse a FlashController<dynamic> after disposing it.

### ISSUE THREAD

**Issue by hasanmhallak** [sososdk/flash#56]
Usecase:
Make a dialog dismissible so the user can dismiss it, but at the same time I want to dismiss the dialog after a delay if the user hasn't already dismissed it.

Problem:
There an assertion in the dismiss function that throws if we try to dismiss something that is already dismissed.
```Dart
  Future<void> dismiss([T? result]) {
    assert(!_transitionCompleter.isCompleted,
        'Cannot reuse a $runtimeType after disposing it.'); // <---------- here
    _dismissed = true;
    _result = result;
    if (onWillPop != null) route?.removeScopedWillPopCallback(onWillPop!);
    _removeLocalHistory();
    _cancelTimer();
    return _controller.reverse();
  }
```
Possible solution:
Changing the assertion line to an if statement that return if the transition completed.
```Dart
  Future<void> dismiss([T? result]) async {
    // assert(!_transitionCompleter.isCompleted,
    //     'Cannot reuse a $runtimeType after disposing it.');
    if (_transitionCompleter.isCompleted) {
      return;
    }
    _dismissed = true;
    _result = result;
    if (onWillPop != null) route?.removeScopedWillPopCallback(onWillPop!);
    _removeLocalHistory();
    _cancelTimer();
    return _controller.reverse();
  }
```

**Comment by sososdk** [comment]
Hi, can the [`duration`](https://github.com/sososdk/flash/blob/1521fafd947cfabe3c16867532980233155d8408/lib/flash.dart#L42) parameter meet your needs?

**Comment by hasanmhallak** [comment]
Thanks for the quick replay.
Actually yes, it would help. I was wondering though what's the consequences if we change the the assertion to an if statement? I make a pull request with these changes sososdk/flash#57

**Comment by hasanmhallak** [comment]
Also if we add a `duration` parameter, what would happened if we dismiss the dialog before the timer finishes?
