### ISSUE TITLE
Using of ThemeExtension broke the Flash.bar designs

### ISSUE THREAD

**Issue by MSRPRO** [sososdk/flash#59]
Previously on version `2.0.5` I was using `Flash.bar` to display this, please have a look at the screenshot below:

![pic_1](https://user-images.githubusercontent.com/80641133/230059207-60805729-1082-4981-a8cc-33bedb5f28d4.jpg)

Now, after the update to `3.0.0` version, I had to use this as per the docs
`extensions: [FlashToastTheme(), FlashBarTheme()]`

And the results were like this, please have a look at the screenshot below:

![pic_2](https://user-images.githubusercontent.com/80641133/230059536-1ece8c24-d698-4b66-9d2a-6ac904fa6c29.jpg)

Unfortunately, there is a white rounded background that I'm unable to remove, also I could not make the border of the green box rounded, can you please provide the docs on how to customize the styles in the new version?

**Comment by sososdk** [comment]
Please refer to:
https://github.com/sososdk/flash/blob/e024a246962fb9461d0165798805c803c271bde4/example/lib/main.dart#L232
