### ISSUE TITLE
Enhancement: Use peanut package and create a live demo using github pages

### ISSUE THREAD

**Issue by apgapg** [sososdk/flash#6]
Hi thanks for creating flash. Just a scope of enhancement. One can be able to view live on repo github page. You can mention the url in README.md. 
This help to try the sample without running the example manually.

Let me know if you need PR.

**Comment by sososdk** [comment]
Hi @apgapg , Welcome PR.

**Comment by sososdk** [comment]
Hi @apgapg , I made a github pages.

**Comment by apgapg** [comment]
Great... Thanks a lot. Just one more suggestion. Add a LIVE DEMO in readme also. Currently you mentioned it in description, do mention in README also.
