### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by sachindayl** [sososdk/flash#60]
I'm getting this error on `final barTheme = theme.extension<FlashBarTheme>()!;` 

can you please direct me on how to fix this? this started happening after upgrading to 3.0.0

**Comment by sososdk** [comment]
Hi, @sachindayl 
Please refer to: https://github.com/sososdk/flash/blob/ec729f8ea8c3dc02c4724b4be1b919dbccf3264e/example/lib/main.dart#L41
