### ISSUE TITLE
Force disable safe area in FlashBar widget

### ISSUE THREAD

**Issue by ton252** [sososdk/flash#61]
I think for some cases it will be useful to add an opportunity to force turn off safe area in FlashBar. I propose to add a bool property to constructor FlashBar.
And change this lines in code:
```
child = widget.safeArea ? SafeArea(
          bottom: position == FlashPosition.bottom,
          top: position == FlashPosition.top,
          child: child,
) : child;
```

**Comment by sososdk** [comment]
Does this seem to be no different from `FlashBehavior.floating`?
