### ISSUE TITLE
Unable to set background using Linear Gradient

### ISSUE THREAD

**Issue by sosualfred** [sososdk/flash#67]
Flash version 2.0.5 had a `backgroundGradient` property for setting a background using a gradient.

In version 3.0.5 this property is no longer available. and I am unable to set a background using linear gradient.

![image](https://github.com/sososdk/flash/assets/22264939/9aa54694-c159-4f59-9444-487cb4e17680)

**Comment by sososdk** [comment]
Hi @sosualfred , please use `flash: ^3.0.5+1` with  the `builder` param.

```dart
context.showFlash<bool>(
  builder: (context, controller) => FlashBar(
    ......
    builder: (context, child) {
      return DecoratedBox(
        decoration: BoxDecoration(
          gradient: LinearGradient(colors: [Colors.black, Colors.red]),
        ),
        child: child,
      );
    },
  ),
);
```
