### ISSUE TITLE
StatusBar brightness changes

### ISSUE THREAD

**Issue by Linaks** [sososdk/flash#69]
Hello,

is there any reason that the status bar brightness is changing if a flashbar is shown?
I use a dark template and if I show a flashbar the brightness changes to dark, which makes the status bar information unreadable.

**Comment by sososdk** [comment]
Status bar brightness may be affected by the background color of the Flashbar. Reference:https://github.com/sososdk/flash/blob/387dac6fcd6f4b2fa415accd3824ac8313104fc0/lib/src/flash.dart#L584

**Comment by Linaks** [comment]
Ah I see it's depending on the background color of the FlashBar.
The problem is, that I set it to white. So if it's white, it assumes that I want to have `SystemUiOverlayStyle.dark`, which is wrong. So I just set the `AnnotatedRegion` to `SystemUiOverlayStyle.light` over my Scaffold.

**Comment by sososdk** [comment]
Why is it wrong? Can you show your code?

**Comment by Linaks** [comment]
```dart
FlashBar(
  controller: controller,
  shouldIconPulse: false,
  shadowColor: Colors.black.withOpacity(0.16),
  backgroundColor: Colors.white.withOpacity(0.92),
  margin: EdgeInsets.all(8),
  behavior: FlashBehavior.floating,
  position: FlashPosition.top,
  icon: icon,
  title: Text('Title'),
  content: Text('Test'),
)
```

**Comment by sososdk** [comment]
> **Flashbar:**
> 
> ```dart
> FlashBar(
>   controller: controller,
>   shouldIconPulse: false,
>   shadowColor: Colors.black.withOpacity(0.16),
>   backgroundColor: Colors.white.withOpacity(0.92),
>   margin: EdgeInsets.all(8),
>   behavior: FlashBehavior.floating,
>   position: FlashPosition.top,
>   icon: icon,
>   title: Text('Title'),
>   content: Text('Test'),
> )
> ```
> 
> **MaterialApp ThemeData**
> 
> ```dart
> ThemeData(
>           useMaterial3: true,
>           scaffoldBackgroundColor: Colors.black,
>           colorScheme: const ColorScheme.dark().copyWith(
>             background:  Colors.black,
>             surface:  Colors.black,
>             surfaceTint:  Colors.black,
>             primary: Colors.white,
>             secondary: Colors.black,
>           ),
>         )
> ```

It's the expected effect:
![image](https://github.com/sososdk/flash/assets/46806014/59c6b2c9-30c9-4433-8ba7-dba218a000bc)

**Comment by Linaks** [comment]
Thank you very much! It seems like I've to find out, where exactly it goes wrong.
